# Generated by Django 4.2.7 on 2024-01-22 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosapp', '0003_userformadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorupload',
            name='Dr_name',
        ),
    ]
